FROM java:8
EXPOSE 8761
ADD target/note-application-eureka-server-0.0.1-SNAPSHOT.jar note-application-eureka-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","note-application-eureka-server-0.0.1-SNAPSHOT.jar"]
